[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "store2hydro"
version = "0.1.0"
description = "Core framework for Store2Hydro modelling"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["."]
